name: Auto Rebase PRs

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  autorebase:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup git
        run: |
          git config --global user.name "merge-bot"
          git config --global user.email "actions@github.com"

      - name: Fetch branches
        run: |
          git fetch origin main
          git fetch origin ${{ github.head_ref }}

      - name: Checkout PR branch
        run: |
          git checkout ${{ github.head_ref }}

      - name: Attempt rebase
        run: |
          git rebase origin/main || true

      - name: Auto resolve simple conflicts
        run: |
          git diff --name-only --diff-filter=U | while read file; do
            echo "Resolving $file using PR version"
            git checkout --ours "$file"
            git add "$file"
          done

      - name: Continue rebase
        run: |
          git rebase --continue || true

      - name: Push branch
        run: |
          git push origin HEAD --force-with-lease
